/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_itxtech_mirainative_Bridge */

#ifndef _Included_org_itxtech_mirainative_Bridge
#define _Included_org_itxtech_mirainative_Bridge
#ifdef __cplusplus
extern "C" {
#endif
#undef org_itxtech_mirainative_Bridge_PRI_MSG_SUBTYPE_FRIEND
#define org_itxtech_mirainative_Bridge_PRI_MSG_SUBTYPE_FRIEND 11L
#undef org_itxtech_mirainative_Bridge_PERM_SUBTYPE_CANCEL_ADMIN
#define org_itxtech_mirainative_Bridge_PERM_SUBTYPE_CANCEL_ADMIN 1L
#undef org_itxtech_mirainative_Bridge_PERM_SUBTYPE_SET_ADMIN
#define org_itxtech_mirainative_Bridge_PERM_SUBTYPE_SET_ADMIN 2L
#undef org_itxtech_mirainative_Bridge_MEMBER_LEAVE_QUIT
#define org_itxtech_mirainative_Bridge_MEMBER_LEAVE_QUIT 1L
#undef org_itxtech_mirainative_Bridge_MEMBER_LEAVE_KICK
#define org_itxtech_mirainative_Bridge_MEMBER_LEAVE_KICK 2L
#undef org_itxtech_mirainative_Bridge_GROUP_UNMUTE
#define org_itxtech_mirainative_Bridge_GROUP_UNMUTE 1L
#undef org_itxtech_mirainative_Bridge_GROUP_MUTE
#define org_itxtech_mirainative_Bridge_GROUP_MUTE 2L
/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    loadNativePlugin
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_loadNativePlugin
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    disablePlugin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_disablePlugin
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    enablePlugin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_enablePlugin
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    eventStartup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_eventStartup
  (JNIEnv *, jobject);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    eventExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_eventExit
  (JNIEnv *, jobject);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    eventEnable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_eventEnable
  (JNIEnv *, jobject);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    eventDisable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_eventDisable
  (JNIEnv *, jobject);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    eventPrivateMessage
 * Signature: (IIJLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_eventPrivateMessage
  (JNIEnv *, jobject, jint, jint, jlong, jstring, jint);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    eventGroupMessage
 * Signature: (IIJJLjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_eventGroupMessage
  (JNIEnv *, jobject, jint, jint, jlong, jlong, jstring, jstring, jint);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    eventGroupAdmin
 * Signature: (IIJJ)V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_eventGroupAdmin
  (JNIEnv *, jobject, jint, jint, jlong, jlong);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    eventGroupMemberLeave
 * Signature: (IIJJJ)V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_eventGroupMemberLeave
  (JNIEnv *, jobject, jint, jint, jlong, jlong, jlong);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    eventGroupBan
 * Signature: (IIJJJJ)V
 */
JNIEXPORT void JNICALL Java_org_itxtech_mirainative_Bridge_eventGroupBan
  (JNIEnv *, jobject, jint, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    callIntMethod
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_itxtech_mirainative_Bridge_callIntMethod
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_itxtech_mirainative_Bridge
 * Method:    callStringMethod
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_itxtech_mirainative_Bridge_callStringMethod
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
