name: Native Build
on: [ push, pull_request ]

jobs:
  check:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Native Build
        working-directory: native
        run: >
          msbuild native.sln
          -t:rebuild
          -p:Configuration=Release
          -p:Platform=x86
          -p:AssemblyName=CQP

      - name: Native Upload
        uses: actions/upload-artifact@v3
        with:
          name: native-build
          path: native/Release

      - name: CQP Move
        run: copy src\main\resources\CQP.dll native\Release\CQP.dll

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew assemble --scan

      - name: Mirai Plugin Build
        run: ./gradlew buildPlugin --scan

      - name: Mirai Plugin SHA1SUM
        shell: bash
        working-directory: build/mirai
        run: find . -name "*.jar" -type f -exec sh -c "sha1sum {} | cut -b-40 > {}.sha1" \;

      - name: Mirai Plugin Upload
        uses: actions/upload-artifact@v3
        with:
          name: mirai-plugin-build
          path: build/mirai
